name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [[ubuntu-latest,x64-linux,clang]]
        buildType: [Release]
    runs-on: ${{ matrix.os[0] }}

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or run vcpkg
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgGitCommitId: 'a0454d6e18b335cf12da34d925538897d598219b'
          runVcpkgInstall: true
          vcpkgJsonGlob: '**/vcpkg.json'
          appendedCacheKey: vcpkginstall

      - name: Run CMake with Ninja
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ci-default'
          buildPreset: 'ci-build'

      - name: Upload protobuf generated files
        uses: actions/upload-artifact@v2
        with:
          name: opengloves_protocol
          path: ${{ github.workspace }}/builds/ci-default/protos